fix ci
Change-Id: Ia203ef08f24be23111baa628fcb234c812b50cd1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,7 +34,18 @@ jobs:
       - name: Run go build
         run: |
           go build ./...
-          
+      - name: Install gofumpt
+        run: |
+          go install mvdan.cc/gofumpt@v0.5.0
+
+      - name: Run gofumpt
+        run: |
+          gofumpt -l -w . 
+          if ! test -z "$(gofumpt -d -e . | tee /dev/stderr)"; then
+            echo "❗️ gofumpt check failed"
+            exit 1
+          fi
+
       - name: Run tests with coverage
         run: |
           go test -race -coverprofile=coverage.out $(go list ./... | grep -v /examples/)
